// Single entry point shared by the desktop binary (main.rs) and the
// mobile entry points generated by `tauri android init` / `tauri ios init`.

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_deep_link::init())
        .setup(|_app| Ok(()))
        .run(tauri::generate_context!())
        .expect("error while running Ipswich News");
}
